### ISSUE TITLE
signTextJS not working with Firefox 50.0beta10

### ISSUE THREAD

**Issue by pivanov83** [mozkeeler/signTextJS#45]
Hello,
SignTextJS 0.7.4 is not working with Firefox 50.0beta. It gives TypeError: cert.getUsagesString is not a function main.js:306:5. Line 306:5 is     cert.getUsagesString(true, {}, usages); // true for local-only verification.

**Comment by julien2512** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1284946

**Comment by rbatllet** [comment]
It seems it has been solved in 0.7.5

**Comment by julien2512** [comment]
@BDevSEPLPPOL may be you should check it out ?

**Comment by pivanov83** [comment]
this has been fixed. Closing issue
